NRCan/geo-deep-learning

README.md
conf/config.yaml
image_classification.py
models/model_choice.py
utils.py

Ensure continuity of images when classifying

---

image_classification.py
images_to_samples.py
train_model.py
utils.py

Fixed some small AWS errors, added to docstring, added a validation to download shp files only once from AWS, and fixed state dictionary key to 'model' in last_epoch.pth.tar

Made some modifications to work with AWS and filled in docstring

---

.travis.yml
README.md
augmentation.py
image_classification.py
images_to_samples.py
models/TernausNet.py
models/checkpointed_unet.py
models/inception.py
models/model_choice.py
models/unet.py
train_model.py
utils.py

Store input images as float32 instead of uint8 in hdf5 files

---

conf/config.yaml
conf/config_ci_tst.yaml
conf/config_ci_tst2.yaml
images_to_samples.py
models/unet.py

Added parameter in the config.yaml to mask (or not) the label raster where corresponding pixels in the input image are set to "nodata". 
Previously, the label raster was always masked.

Added boolean parameter to mask label img if input data has nodata value

---

image_classification.py
images_to_samples.py
logger.py
train_model.py

- Fixes #47  
- Code refactoring for function to log info.

Replace put_object function

---

logger.py
train_model.py

* Major changes to logger.py
* Add progress log in train_model.py
I've checked "Allow edits from maintainers", so you can commit into this branch on my fork. Do any changes you like.
Cheers!

Hypertrainer support

---

inference.py

Untested, merged from old code! (I don't have the necessary data on my side to run it anymore)

Fixup attempt for overlap artefacts in segm inference

---

README.md
augmentation.py
conf/config.yaml
conf/config_ci_segmentation_local.yaml
train_model.py

- Configurable augmentation functions (closes #78)  
- Support for PyTorch 1.2.0 (closes #77)
- Updated README
- Fixed horizontal flip. (now uses [contiguous array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ascontiguousarray.html))

Configurable augmentation functions and support for PyTorch 1.2.0

---

README.md
conf/config.yaml
conf/config_ci_classification_local.yaml
conf/config_ci_segmentation_local.yaml
train_model.py
utils.py

Support for multi-GPUs using data parallel.  
The number of GPUs to use is configurable in the yaml.  
Closes #83

Support for multi-GPUs using data parallel

---

README.md
conf/config.yaml
conf/config_ci_classification_local.yaml
conf/config_ci_segmentation_local.yaml
images_to_samples.py
inference.py
models/TernausNet.py
models/model_choice.py
train_model.py
utils/utils.py

- conf/config.yaml: remove models parameter section
- inference.py: optionally input a directory with .tif files instead of a .csv
- inference.py: add debug mode.
- utils/model_choice.py: returns state_dict instead of path to state_dict
- utils/utils.py: add tolerance in assigning GPU to task, if some memory is used (ex.: 10%) and some usage existing (ex.: 10%)
- images_to_samples.py, inference.py and train_model.py: create output directory automatically with pathlib

Delete models parameter section, automatically manage output dir, etc.

---

inference.py

Temporary fix to manage inconsistencies between provided number of band and image number of band at inference

Temporary fix for inconsistencies between provided number of band and img nb band.

---

conf/config_ci_segmentation_local.yaml
data/images_to_samples_ci_csv.csv
inference.py
train_segmentation.py
utils/logger.py
utils/metrics.py

- Added classwise and mean IOU functionalities.

classwise and mean IOU

---

conf/config_ci_segmentation_local.yaml
data/images_to_samples_ci_csv.csv
train_segmentation.py
utils/logger.py
utils/metrics.py

- In the near future when all pull request has being merged, we have to switch the develop branch to Default

Update develop with Master

---

.travis.yml
README.md
images_to_samples.py
models/model_choice.py
train_segmentation.py
utils/augmentation.py

Implementation of segmentation PyTorch models in GDL and other code fixes and improvements.

Segmentation PyTorch Models and other fixes 

---

losses/__init__.py
losses/boundary_loss.py
losses/dice_loss.py

New loss functions added (Boundary loss and Dice Loss, Duo Loss)

New loss functions

---

gdl_hyperopt_template.py

Using hyperopt with GDL for hyperparameter optimization
ToDo:

[WIP] Add hyperopt template

---

config/README.md
images_to_samples.py

Add option to use pseudo stratification to balance class proportions between the training and validation set.

Add pseudo stratification

---

inference_segmentation.py

fix inference progress bar

---

README.md
train_segmentation.py

Finalize removal of PR #109 features flagged for deprecation in #220 .

remove more from PR#109

---

config/augmentation/basic_augmentation_segmentation.yaml
train_segmentation.py

reimplement crop_size and rename to prevent confusion with hdf5 samples

---

.github/workflows/github-actions-ci.yml
inference_segmentation.py

Hotfix for windows user

---

config/ccmeo_production.yaml
config/dataset/ccmeo_datacube_dataset.yaml
config/training/default_training.yaml
train_segmentation.py
utils/utils.py

Change in yamls for making sampling and training work out of the box, plus removing some useless line in training.

make it work for all

---

environment.yml
train_segmentation.py
utils/utils.py

to close the issues [#283](https://github.com/NRCan/geo-deep-learning/issues/283)

remove the dependence for pynvml

---

utils/metrics.py

fixes #351 (at least for single GPU use, not tested on multi-gpu)

metrics.py: push metric to same device as prediction and label

---

environment.yml

Bump torchgeo version from 0.2 to 0.3

---

train_segmentation.py

train_segmentation.py: convert bands to string before naming checkpoint

---

train_segmentation.py

train_segmentation.py: fix "bands" parameter name

---

environment.yml

environment.yml: restore pynvml

---

dataset/aoi.py
tests/dataset/test_aoi.py
tests/test_tiling_segmentation.py
tiling_segmentation.py
utils/geoutils.py
utils/verifications.py
verify_segmentation.py

geoutils.py: copy core functions from solaris to GDL (abandon solaris progressviely)

---

utils/utils.py

utils.py: remove boto3 import

---

inference_segmentation.py
train_segmentation.py
utils/augmentation.py
utils/create_dataset.py

related to #300 
replace "sat_img" and "map_img" keys to "image" and "mask" respectively (matching torchgeo standard)

Align GDL's SegmentationDataset to torchgeo standard - first step

---

.github/workflows/build-push-on-release.yml
Dockerfile

1. Added a Dockerfile which covers all processes for building a custom docker image (GDL + projectRegularization)
2. Added GitHub Actions script to automatically build a docker image and push it to the DockerHub repository

401-build-push-automation

---

GDL.py
dataset/aoi.py
tests/dataset/test_aoi.py
tests/tiling/tiling_segmentation_binary_ci.csv
utils/geoutils.py
utils/visualization.py

fixes #396, #404
Fixed vis() function
Fixed subset_multiband_vrt() function
Minor syntax fixes

PR to fix #396 and #404

---

tests/utils/test_geoutils.py
utils/geoutils.py

fixes #411 
test_geoutils.py: add test for this case
also: add compress='lzw' to output raster parameters. I don't think this addition is worth an issue/PR of its own, but can certainly create one if needed.

create_new_raster_from_base: Remove if statement for singleband output array

---

config/tiling/default_tiling.yaml

default_tiling.yaml: no clahe by default

---

dataset/aoi.py

aoi.py: add progress and aoi_id in progress bar

---

tests/dataset/test_aoi.py

Temporary fix for github CI's hanging with test_for_multiprocessing()

---

dataset/create_dataset.py
utils/metrics.py

returned ComputePixelMetrics because it was still used in the evaluate_segmentation script

Fix evaluate segmentation script

---

dataset/create_dataset.py
utils/metrics.py

the update makes the tiling script robust to different type of label geometry, including curves

fix for the tiling in case of non-polygon geometry

---

config/inference/default_binary.yaml
config/inference/default_multiclass.yaml
dataset/aoi.py
dataset/stacitem.py
inference_segmentation.py
tests/dataset/test_aoi.py
tests/dataset/test_stacitem.py
utils/geoutils.py

Related to #222 
aoi.py: move stac class to its own file (dataset/stacitem.py)
test_stacitem.py: move stac-specific tests from test_aoi.py to test_stacitem.py

inference_segmentation.py: add support for stac item as direct input

---

inference/InferenceDataset.py
inference/SingleBandItemEO.py
inference_segmentation.py
postprocess_segmentation.py
utils/geoutils.py

1. Download the footprint from the stac-item during the inference, if included.
2. Clip the predicted gpkg outside the footprint after the postprocessing.

add clipping gpkg to not go over the image(s)

---

utils/geoutils.py

New feature, function added in `geoutils.py` converting shapely Multypolygon to Polygon inside a geodataframe. 
Take a Path to the GPKG and the layer name, I will change the layer name to optional in the future to be use on other configurations. 
Close  #443

New Feature - function converting Multipolygon to Polygon 

---

inference_segmentation.py

inference: update and add overrides from model params

---

tests/utils/test_geoutils.py
utils/geoutils.py

Adding a test for the `multi2poly` function in `geoutils.py`. 
Also adding more information on this function documentation.
Note, in the test the `tests/data/new_brunswick_aerial/BakerLake_2017_clipped.gpkg` have is Multipolygon convert into Polygon, I verified that anything run normally after that, so no worry.

Test - Adding a test for the multi2poly function

---

inference_segmentation.py

inference_segmentation.py: softcode download data bool and data_dir

---

dataset/aoi.py
tests/data/all_gpkg.csv
tests/utils/test_geoutils.py
utils/geoutils.py

aoi.py: fix vertices calculation with shapely

---

.github/workflows/build-on-tag.yml

build-on-tag.yml: change trigger for docker image

---

config/model/smp_manet.yaml
config/model/smp_pan.yaml
config/model/smp_unet-spacenet-senet154.yaml
config/model/smp_unetplusplus.yaml
tests/dataset/test_aoi.py
tests/model/test_models.py
tests/optimizer/test_optimizers.py
tests/test_tiling_segmentation.py
tests/tiling/test_tiling.py

Fix #497, by changing the path of some `for` loop and removing some if-else statements to upgrade the cover to 100% (or close).

Fixe the cover of the tests already in place

---

config/inference/default_binary.yaml
inference_segmentation.py
utils/inference.py

added reference article to the docstring
added use_hanning bool as a config parameter
added logging info to indicate smoothening vs non-smoothening
closes #505

Minor fixes for smoothening with hann 

---

inference_segmentation.py
tiling_segmentation.py
utils/aoiutils.py
utils/utils.py
verify_segmentation.py

Change place the from `aois_from_csv` to utils directory since some change detection functions is added.

Change place for some aoi function and add some change detection functions

---

.github/pull_request_template.md
README.md
docs/source/index.rst

PR template

---

environment.yml

Fixes #534 
Tested locally with Docker

environment.yml: restore previous version

---

Dockerfile

Fixes #540 
Docker image created locally. Successful.
If you're unsure about any of these, don't hesitate to ask. We're here to help! 
- [] My code includes tests that show that my feature works
_If your PR does not fulfill all of the requirements in the checklist above, that's OK!_ If you need help, @-mention a maintainer and/or add the __Status: Help Needed__ label.

Dockerfile: conda install libarchive

---

docs/.readthedocs.yaml
docs/requirements.txt

Fix the new file management for readthedoc.
- Bug fix (non-breaking change which fixes an issue)

add the new requirements
