NRCan/geo-deep-learning

- config/dataset/README.md
- config/dataset/test_ci_segmentation_dataset.yaml
- data/images_to_samples_ci_csv.csv
- inference_segmentation.py
- sample_creation.py
- sampling_segmentation.py
- utils/geoutils.py
- utils/utils.py
- utils/verifications.py
reimplement target_ids
rename target_ids to attribute_values (more meaningful in GIS vocabulary: attribute table, attribute field, attribute values, etc.)
move attribute field input from csv to yaml
add documentation for dataset configuration
closes #251
> Reimplement target_ids, refactoring and use yaml not csv to set attribute field

- config/gdl_config_template.yaml
- config/model/deeplabv3_resnet101_dualhead.yaml
- config/training/default_training.yaml
- inference_segmentation.py
- models/model_choice.py
- tests/loss/test_losses.py
- tests/model/test_models.py
- train_segmentation.py
- utils/loss.py
- utils/utils.py
- adapt train_segmentation.py and inference_segmentation.py to new usage
- move state_dict_path param to default_training.yaml
- implement unit tests for model_choice.py functions
- read_checkpoint(): add robustness (covers external checkpoints with only model weights, and complies to torch's save key naming standard 'model_state_dict' and 'optimizer_state_dict' rather than gdl's 'model' and 'optimizer' keys while being retrocompatible to old gdl models
- create high level define_model() function using all low level models definition/loading functions from model_choice.py
- test_losses.py: implement class weights test
- softcode strict loading boolean for loading provided state_dict at train_segmentation.py
fixes #292
> refactor model_choice.py using solution in issue #292 and more

- environment.yml
Fix conda environment for #304 and next.
Adapted from #275 :
add dependency: torchgeo, pystac, solaris (v0.5.0), rio-stac
move pip dependencies to conda if possible
change channel priority (pytorch, then conda-forge)
remove secondary dependencies when possible
> environment.yml: fix and update

- inference_segmentation.py
While we wait for Pytorch Lightning to be implemented, I tested the torch automatic mixed precision AMP on QC10P001, for inference. Times are for raster prediction only.  
Original time for inference : 61m.59s    
Time for inference with AMP : 37m43s   
Number of Pixels that are different between both predictions : 20 (out of 403 605 000 pixels total).   
It also reduces the GPU memory needed (slightly).  
Configuration:   
I used Vic's NRG hydro model and tested it on Velum.
> Add automatic mixed precision (amp) for inference

- .github/workflows/github-actions-ci.yml
The smallest PR we've seen in a while. Attemps to fix CI on NRCAN's repo. The problem is related to [the coverage tool not finding a file](https://stackoverflow.com/questions/2386975/no-source-for-code-message-in-coverage-py), that at first glance, seems to have no impact if missing. Might as well ignore the problem raised by coverage and causing the CI to fail.
> Coverage report: ignore error (fixes CI)

- dataset/aoi.py
- evaluate_segmentation.py
- tests/dataset/test_aoi.py
- tiling_segmentation.py
- verify_segmentation.py
fixes #362 
A new method in the AOI class defines a "raster_name" attribute, used mainly for printing during execution, but also as output name of multiband raster if ["write_multiband == True"](https://github.com/NRCan/geo-deep-learning/blob/develop/dataset/aoi.py#L154). 
For the "raster_name" attribute, I decided to suffix the name with bands requested as suggested by @ms888ekb 
For example:
input:"tests/data/spacenet/SpaceNet_AOI_2_Las_Vegas-056155973080_01_P001-WV03-${dataset.bands}.tif" 
bands requested: ["R", "G", "B"]
"raster_name" output: "tests/data/spacenet/SpaceNet_AOI_2_Las_Vegas-056155973080_01_P001-WV03-RGB_**R-G-B**.tif"
You'll also notice that when more than 4 bands are requested, the suffix "raster_name" will become the actual number of bands, not the names of bands …
> AOI handling with VRT

- CITATION.cff
I've created a citation file that can be used in github to automatically populate a reference option on the left side bar of the main repo page. 
I used information from github [resource](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files), information from issues #230, and used [this tool](https://citation-file-format.github.io/cff-initializer-javascript/#/)
> included citation file for github

- GDL.py
- inference_segmentation.py
After the merge of the acceleration of the inference I forgot to had a `break` in the for loop when looking to the max GPU RAM. 
This PR will fix it. 
Adding to that, a error message was appearing for hydra when not specifying the version use for the code, so I add `None` to stop that message. When we put `None` it will use the last version installed in our case at the moment it's 1.2.
> Quick: fix max GPU RAM finder and remove an hydra error msg

- dataset/aoi.py
- verify_segmentation.py
fixes #422
fixes #423
The fix was aimed at the same line of code, thus creating a single PR for these two issues.
> aoi.py: in to_dict(), format raster's metadata & use coma delimiter in verify report as csv

- dataset/aoi.py
- tests/test_tiling_segmentation.py
PR #421 has introduced a bug, where equalization parameters are no longer passed in aois_from_csv(). 
Also, the variable name returned from equalizate_hist_raster in AOI's \_\_init__ hadn't been updated with last refactoring (self.raster_multiband --> self.raster_dest)
Hopefully this kind of bug won't go unnoticed too often as, in this case, it caused the equalization to be skipped (aois_from_csv() not passing down params) or equalized rasters to be ignored during tiling (with tiling.multiprocessing=True, the tiling read the self.raster_dest when the equalized raster was, in fact, under self.raster_multiband...).
> Fix equalization during tiling

- inference_segmentation.py
- tests/utils/test_geoutils.py
- utils/geoutils.py
New feature, function added in geoutils.py to fetch information save into tag inside a rasterio file. 
Also save checkpoint inside the inference raster at the end of `inference_segmentation.py`. This part is temporary, the tag information will be use via `create_new_raster_from_base` in the future.
This is necessary to tackle the #442 issue otherwise the GPKG will miss information.
> New Feature - function fetching tag information to raster

- inference_segmentation.py
- tests/utils/test_utils.py
- utils/utils.py
Fix #476 by moving the exception at the end of the function and adding a test to the mix.
> Resolving the raising error when `get_key_def` not match the expected type

- config/inference/README.md
- config/inference/default_binary.yaml
- config/inference/default_multiclass.yaml
- dataset/README.md
- inference_segmentation.py
fixes #472 (oups the PR branch has wrong number!)
inference_segmentation.py:
- implement output_path and name heatmap and temp file accordingly
- replace aoi.raster_name to aoi.aoi_id for cleaner log README.md: update inference and aoi READMEs
default_binary.yaml: add output_path
default_multiclass.yaml: idem
> Inference: implement user-chosen output path

- evaluate_segmentation.py
- inference_segmentation.py
- tests/utils/test_utils.py
- utils/utils.py
inference_segmentation.py: restore str as expected type to better reflect documentation
Documentation for "expected_type" in get_key_def(): [:param expected_type: (type) type of the expected variable.](https://github.com/NRCan/geo-deep-learning/blob/develop/utils/utils.py#L142)
To me, this suggests that the input variable must bear this "expected_type". It feels confusing to expected a type that is actually one that is assigned during the get_key_def() function, "Path" in this case.
@CharlesAuthier is this slight retroactive change ok to you?
> utils.py/get_key_def(): allow "expected_type=str" even with "to_path=True" param

- inference_segmentation.py
- tests/utils/test_geoutils.py
- utils/geoutils.py
Adding a tag containing the `classes_dict` parameter, find in the dataset yaml, to the output raster after inference.
Also adding a tests to verify the output,  **important** to use the `fetch_tag_raster` function to fetch the `classes_dict`, otherwise the output will be a string and not a dictionary.
> Add Tag with classes dict to inference raster

- inference_segmentation.py
- utils/geoutils.py
fixes #525 
In the [GDAL doc](https://gdal.org/drivers/raster/gtiff.html), nothing seems problematic with always writing BIGTIFF. The only requirement is to have libtiff > 4.0, which has also been the case in our conda envs. I check all our conda envs and docker images and they all include libtiff >4.0.
This solution also uses tiled=True and defines blocksizes in the tif, as suggested by [this SO post](https://gis.stackexchange.com/questions/347765/how-to-write-bigtiff-raster-files-with-rasterio).
> geoutils.py: force BIGTIFF

- config/model/gdl_hrnet.yaml
- docs/source/model.rst
- models/hrnet/backbone.py
- models/hrnet/hrnet_ocr.py
- models/hrnet/ocr.py
- models/hrnet/ocr_modules.py
- models/hrnet/utils.py
- models/segformer.py
- tests/model/test_models.py
- train_segmentation.py
Thank you for submitting your **PR** and helping us with **GDL**.
Please read the template below, fill it out as appropriate, and make additional changes to your code as needed. 
Please feel free to submit your PR even if it doesn't satisfy all of the requirements below.
If you need assistance or review from a maintainer, add the label __Status: Help Needed__ or __Status: Review Needed__ respectively.
After review, a maintainer will add the label __Status: Revision Needed__ if further work is required for the PR to be merged.
HRNet+OCR model architecture. 
Fixes #543 
If the added changes are already cover by tests, skip that section.
Otherwise, please describe tests that you added to the pytest …
> added HRNet+OCR, minor changes

- config/gdl_config_template.yaml
- config/training/default_training.yaml
- tests/utils/test_script_model.py
- train_segmentation.py
- utils/script_model.py
Thank you for submitting your **PR** and helping us with **GDL**.
Please read the template below, fill it out as appropriate, and make additional changes to your code as needed. 
Please feel free to submit your PR even if it doesn't satisfy all of the requirements below.
If you need assistance or review from a maintainer, add the label __Status: Help Needed__ or __Status: Review Needed__ respectively.
After review, a maintainer will add the label __Status: Revision Needed__ if further work is required for the PR to be merged.
Please include a summary of the change and which issue is resolved (if applicable). 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
If it fixes an open issue, please link to the issue here.
Fixes #558 …
> 558 implement a base class for scripting models

- environment.yml
- evaluate_segmentation.py
- tiling_segmentation.py
- utils/geoutils.py
If it fixes an open issue.
Fixes #570 
If the added changes are already cover by tests, skip that section.
Otherwise, please describe tests that you added to the pytest codebase (if applicable).
If you're unsure about any of these, don't hesitate to ask. We're here to help! 
_If your PR does not fulfill all of the requirements in the checklist above, that's OK!_ If you need help, @-mention a maintainer and/or add the __Status: Help Needed__ label.
> 570 bug remove solaris

- .dockerignore
- Dockerfile
- config/inference/default_binary.yaml
- config/inference/default_multiclass.yaml
- docs/source/mode.rst
- environment.yml
- inference_segmentation.py
- tests/CI/test_gh_actions_ci.py
- tests/dataset/test_aoi.py
- tests/dataset/test_datasets.py
- tests/dataset/test_stacitem.py
- tests/test_tiling_segmentation.py
- tests/test_verify_segmentation.py
- tests/tiling/test_tiling.py
- tests/utils/test_geoutils.py
- tests/utils/test_utils.py
- utils/script_model.py
This PR updates the parameters from geo-inference (workers, prediction_threshold, patch_size).  
It also reduces the size of the docker image created.  
- Inference integration test  
- On HPC, on multiple images using the image `tst_gdl_3_1.sif` 
If you're unsure about any of these, don't hesitate to ask. We're here to help! 
- [X ] My code follows the code style of this project
- [X ] I have performed a self-review of my own code
- [X ] My PR has a descriptive title
- [X ] My code follows PEP8 (most of it)
- [X ] My code have the proper documentation in the code
- [X ] I have made corresponding changes to the documentation (if applicable)
- [X ] My changes generate no new errors
- [X ] My code is …
> Update geo-inference parameters
